### ISSUE TITLE
Please enable hotkey "Ctrl+Tab" to switch 

### ISSUE THREAD

**Issue by rajq123** [carlosmu/editor_swap#1]
Ctrl+Tab is a universal switch in windows, web browsers, It will be handy to have hotkey because blender people love hotkeys and will use it more frequently. Also if possible please add option to select which workspaces are interchangeable like shador editor to UV editor. geometry nodes to 3d viewport and vice versa, Dopesheet to timeline/graph editor. also if possible make a switch for more than 2 workspace

**Comment by carlosmu** [comment]
Your proposals are very interesting! you can be sure i will consider it very soon . I take this opportunity to invite you to try the addon that I am working on these days https://gumroad.com/l/quicklattice

**Comment by carlosmu** [comment]
> Ctrl+Tab is a universal switch in windows, web browsers, It will be handy to have hotkey because blender people love hotkeys and will use it more frequently. Also if possible please add option to select which workspaces are interchangeable like shador editor to UV editor. geometry nodes to 3d viewport and vice versa, Dopesheet to timeline/graph editor. also if possible make a switch for more than 2 workspace

Hello @rajq123 !!
I change the name of this addon. Now is "Editor Swap". All the features you requested are ready. 
Download here: https://gumroad.com/l/editorswap and tell me your opinion.
I will close this task.
See you!
